node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
      //https://index.docker.io/v2/ v2 failed to authenicate
     docker.withRegistry('https://docker.io', 'dockerhub') {
       //def app = docker.build("aungtrt1018/docker-nodejs-demo:${commit_id}", '.').push()
        def app = docker.build("aungtrt1018/docker-nodejs-demo:${commit_id}", '.')
        app.push()
     }
   }
}
